### PR TITLE
add status_code for response

### PR DESCRIPTION
**Pull request by fferegrino**
Not sure if this is something that you want to do Michael; also, not sure if we should expose the rest of the response parameters...

### CODE REVIEW

**Comment by mikeckennedy** [comment]
Hi @fferegrino Thanks so much for the PR. It looks solid. But I'm having a hard time of seeing when I would use this in a HTML / Web flow outside of APIs which wouldn't use the template wrapper.

What did you have in mind for responses? For 201s that only makes sense in the terms of APIs. For 200s, that's the default. 302 is a return RedirectResponse (approx, class name?). The one that may be something we'd use is 404 and showing a proper error page.

I might just be game to accept this just to make pretty 404s easier, but what else would we do with this capability?

**Comment by fferegrino** [comment]
Yeah, styled 404's was what I had in mind.

**Comment by mikeckennedy** [comment]
Hi @fferegrino 

Thanks again for this PR. It is a good idea to support 404s. But I think I'd like a different way to communicate it.

Let's say you request this URL:

`https://site.com/items/17`

We'd look in the DB, and if there is an item with ID 17, we'd return that to the template and render it. But if it's not found, we want to return the HTML of an error page, the status 404, but leave the URL in place.

I don't see how your PR makes that work without going to a new view/URL. But I love the idea of your PR for this.

So I took the ideas and added the feature. Check it out here:

[github.com/mikeckennedy/fastapi-chameleon#friendly-404s-and-errors](https://github.com/mikeckennedy/fastapi-chameleon#friendly-404s-and-errors)

With this, any time you want a friendly 404 page for a given view, just call `fastapi_chameleon.not_found()`. It'll raise a special exception noticed by this library. That will tell it to render `templates/errors/404.pt` and return a 404 status code but leave the URL in place without redirecting.

Thanks!

**Comment by fferegrino** [comment]
Cool, closing this issue!

**Pull request closed without merging**
